### ISSUE TITLE
How to do multi-level override?

### ISSUE THREAD

**Issue by ericfong** [akaspin/nun#4]
I think nun is really a good idea templating engine
But how can I do multi-level override?

testOverride.html
{{< testBase.html}} 
{{+ content}}
I Am Content
{{/ content}}

testBase.html
{{< testSuperBase.html}} 
{{+ contentWrap}}
<body>
{{+ content}}
{{/ content}}
</body>
{{/ contentWrap}}

testSuperBase.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
{{+ contentWrap}}
{{/ contentWrap}}
</html>

When I render testOverride.html, it give me :
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
</head> 
 <body> 
 </html> 

the content is missing... please help

**Comment by ericfong** [comment]
I have put my code in here : http://gist.github.com/480051

**Comment by akaspin** [comment]
Hi. I'm glad that you liked nun. Unfortunately you made a mistake. From readme about overrides: "Blocks can not be nested." But you are use nested blocks. You can find better examples in `test/fixtures/override-*.html` files. 

If you meet this explanation. Please close issue.

**Comment by akaspin** [comment]
Closing. Described in docs

**Comment by akaspin** [comment]
Ups. Another try
