### ISSUE TITLE
No npm package for nun?

### ISSUE THREAD

**Issue by andris9** [akaspin/nun#5]
I totally love nun, thanks for this module!

Is it possible to make a [npm](http://npmjs.org/) package out of it so I can set it as a dependency for my own programs?

**Comment by akaspin** [comment]
Please give me time until Tuesday.

**Comment by andris9** [comment]
Thanks! No need to hurry though, if nun is going to be a npm package some time in not so far future then its good enough for me :)

Thanks again for a great module!

**Comment by akaspin** [comment]
Closed by akaspin
